### PR TITLE
Documentation topic 1

### PR DESCRIPTION
**Pull request by UO289845**
Fixed the problems detected in the review

### CODE REVIEW

**Comment by uo289267** [comment]
What do you mean by "Apart from being in GitHub the system will have an API responsible of handling the questions generated previously from WikiData."?

**Comment by UO289845** [comment]
There was missinng a coma, now fixed.

Those are two requirements, the first one is that it will be stored and deployed via GitHub, and the second, is two draw more emphasis on the present of the two APIs, ours and the WikiData one. The WikiData one is used by us to generate the questions, and our API is used to send those questions to the game.

**Comment by uo289267** [comment]
I dont think your descriptions are 100% accurate
I would suggest changing it for:

"The system will also store the historical data of the users, thanks to the login and registering service featured in the application, and users will be able to access their information. The application will have at least English as an available language. Moreover, the project will be stored and deployed through GitHub. 
Lastly, the system will give access to non sensitive user's information through a public API as well as another API for the questions generated."


If you want to reference that questions generated through wikidata will be passed to our application it is not done thorugh an API it is done through an interface that connects the question generation and the game. I have referenced in the text the apis that need to be public based on the lab description document. 

I would suggest to put the text that I have rephrased instead of yours or discuss its final shape from it.
Another suggestion for the whole section is the use of connectors in the text (Moreover, On the one hand...).

**Comment by UO289845** [comment]
Upon rereading your last comment I've realize that the last line in the paragraph already speaks about the use of the API. My apologies for the misunderstanding.

**Comment by uo289267** [comment]
No worries

**Review by uo289267 — APPROVED** [review]
I consider the changes to be correct

**Pull request merged**
