### PR TITLE
Updating doc

### PR DESCRIPTION
**Pull request by sinne10**
Updated points 7 and 8

### CODE REVIEW

**Comment by ErdemYabaci** [comment]
Hey, I'm encountering this error after I build locally.
image

**Comment by sinne10** [comment]
You might need to download graphviz. Here is the [link](https://graphviz.org/download/). Version 10.0.1 worked for me

**Review by ErdemYabaci — APPROVED** [review]
Alright works after downloading graphviz.

**Comment by uo289267** [comment]
👍

**Pull request merged**
